export const ActionTypes = {
    GET_USERS: 'GET_USERS',
    SELECTED_USER: 'SELECTED_USER',
    REMOVE_SELECTED_USER: 'REMOVE_SELECTED_USER',
    GET_PRODUCTS: 'GET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    GET_PHOTOS: 'GET_PHOTOS'
};